# Site Settings
title: "GABRIEL OSEI"
description: "Data Scientist | Ag-Tech | Gamer"
url: "https://gabriel-git24.github.io"
baseurl: "/portfolio"

# Theme Settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dark"

# Sidebar / Author Profile
author:
  name: "Gabriel Osei"
  bio: "Data Scientist | ML Researcher | Ag-Tech"
  location: "Texas, USA"
  avatar: "me.jpeg" # This puts your photo in the sidebar

# Required Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap

# Defaults for Layouts
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true # This makes your sidebar show up on every page
